import React, {useEffect, useState} from 'react';
import {api, today, Login, FoodForm, ProfileForm, Scanner} from './forms';

const meals={breakfast:['Reggeli','☀'],lunch:['Ebéd','◒'],dinner:['Vacsora','☾'],snack:['Snack','✦']};
const macros=[['protein','Fehérje','#c5ee86',4],['carbs','Szénhidrát','#b4b5fa',4],['fat','Zsír','#ffbd91',9]];
const number=n=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:0}).format(n||0);
const shift=(day,n)=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return d.toLocaleDateString('sv-SE')};
export default function App(){
 const [logged,setLogged]=useState(!!localStorage.token),[day,setDay]=useState(today()),[week,setWeek]=useState([]),[profile,setProfile]=useState(null),[view,setView]=useState('diary'),[modal,setModal]=useState(null),[query,setQuery]=useState(''),[foods,setFoods]=useState([]),[pick,setPick]=useState(null),[grams,setGrams]=useState(100),[meal,setMeal]=useState('breakfast'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const reload=()=>setRevision(v=>v+1);
 useEffect(()=>{if(!logged)return;let active=true;setLoading(true);Promise.all([api('/api/profile'),...Array.from({length:7},(_,i)=>{const date=shift(day,i-6);return api('/api/day/'+date).then(x=>({...x,date}))})]).then(([p,...days])=>{if(active){setProfile(p);setWeek(days)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[logged,day,revision]);
 useEffect(()=>{if(!logged)return;let active=true;const timer=setTimeout(()=>api('/api/foods?q='+encodeURIComponent(query)).then(x=>{if(active)setFoods(x)}).catch(e=>{if(active)setError(e.message)}),220);return()=>{active=false;clearTimeout(timer)}},[query,logged,revision]);
 useEffect(()=>{if(!modal&&!pick)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=e=>{if(e.key==='Escape'){setModal(null);setPick(null)}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',key)}},[modal,pick]);
 if(!logged)return <Login done={()=>setLogged(true)}/>;
 const data=week[6]||{entries:[],totals:{}}, totals=data.totals, calc=profile?.calculation||{}, target=calc.daily_target, consumed=totals.kcal||0, remaining=target==null?null:target-consumed, progress=target?Math.min(100,consumed/target*100):0;
 const recorded=week.filter(d=>d.entries.length),average=recorded.length?recorded.reduce((s,d)=>s+d.totals.kcal,0)/recorded.length:0;
 const openProfile=()=>setModal('profile');
 async function action(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message||'Nem sikerült a művelet.')}finally{setBusy(false)}}
 function choose(f){setPick(f);setGrams(100);setModal(null)}
 function barcode(code){action(async()=>{const r=await api('/api/barcode/'+encodeURIComponent(code));if(r.found)choose(r.food);else setModal({type:'food',barcode:code})})}
 const saveFood=f=>{choose(f);reload()};
 return <><div className="app-shell"><aside className="sidebar"><a className="brand" href="#"><span className="brand-mark">k<span>m</span></span><span>kalória<span>mester</span></span></a><p className="eyebrow">A TE RITMUSOD.</p><nav aria-label="Fő navigáció">{[['diary','◫','Napi napló'],['trends','▥','Statisztika'],['foods','⌕','Ételkönyvtár']].map(([id,icon,label])=><button key={id} className={view===id?'nav-active':''} onClick={()=>setView(id)}><span>{icon}</span>{label}</button>)}<button onClick={openProfile}><span>◎</span>Profil és célok</button></nav><div className="sidebar-bottom"><span className="status-dot"/> Saját tér. Saját tempó.<button onClick={()=>{localStorage.removeItem('token');setLogged(false)}}>Kijelentkezés ↗</button></div></aside>
 <main className="workspace"><header className="topbar"><span className="eyebrow">TUDATOSABB MINDENNAPOK</span><button className="text-button" onClick={()=>{localStorage.removeItem('token');setLogged(false)}}>Kilépés</button><button className="avatar" onClick={openProfile} aria-label="Profil megnyitása">◎</button></header><div className="page-heading"><div><p className="eyebrow">KALÓRIAMESTER / {view==='diary'?'ÁTTEKINTÉS':view==='trends'?'STATISZTIKA':'KÖNYVTÁR'}</p><h1>{view==='diary'?'Egyensúlyban, ma is.':view==='trends'?'Lásd a változást.':'A kedvenceid helye.'}</h1><p className="muted">{view==='diary'?'Apró döntések. Egyre jobb szokások.':view==='trends'?'Valós naplóadatok, átlátható összefüggések.':'Saját ételek és beolvasott termékek, egy helyen.'}</p></div><div className="date-picker"><button aria-label="Előző nap" onClick={()=>setDay(shift(day,-1))}>‹</button><input aria-label="Napló dátuma" type="date" value={day} onChange={e=>e.target.value&&setDay(e.target.value)}/><button aria-label="Következő nap" onClick={()=>setDay(shift(day,1))}>›</button></div></div>
 {error&&<div role="alert" className="notice">{error}<button onClick={()=>setError('')} aria-label="Hiba bezárása">×</button></div>}{loading&&<p role="status" className="muted">Napló betöltése…</p>}
 {view!=='foods'&&<><div className="overview-grid"><section className="energy-card"><div className="card-heading"><span className="eyebrow">NAPI ENERGIÁD</span><span className="pill">{day===today()?'Ma':day}</span></div><div className="energy-body"><div className="energy-copy"><p>{remaining==null?'Eddig elfogyasztottál':remaining<0?'A napi kereted felett':'Ennyi fér még a napodba'}</p><div className="hero-number">{number(remaining==null?consumed:Math.abs(remaining))}<span>kcal</span></div><p className="energy-note">{target?`${number(consumed)} elfogyasztva · ${number(target)} napi cél`:'Állíts be személyes keretet a profilodban.'}</p><button className="light-button" onClick={()=>setModal('search')}>+ Étkezés hozzáadása</button></div><div className="energy-ring"><svg viewBox="0 0 200 200" role="img" aria-label={`A keret ${Math.round(progress)} százaléka elfogyasztva`}><circle cx="100" cy="100" r="82" className="ring-track"/><circle cx="100" cy="100" r="82" className="ring-value" pathLength="100" strokeDasharray={`${progress} 100`}/></svg><div><span>✦</span><strong>{target?Math.round(progress)+'%':'—'}</strong><small>napi keret</small></div></div></div><div className="energy-footer"><span><i/> {target?'Személyre szabott becslés':'A profilod még nincs beállítva'}</span><button onClick={openProfile}>Cél módosítása ↗</button></div></section>
 <section className="panel macro-card"><div className="card-heading"><h2>Makróegyensúly</h2><span className="mini-icon">◌</span></div><p className="muted small">A rögzített makrók energiaaránya</p>{macros.map(([key,label,color,factor])=>{const total=macros.reduce((s,[k,,,f])=>s+(totals[k]||0)*f,0);const pct=total?(totals[key]||0)*factor/total*100:0;return <div className="macro-row" key={key}><div><span><i style={{background:color}}/>{label}</span><strong>{number(totals[key])} <small>g</small></strong></div><div className="track"><div style={{width:pct+'%',background:color}}/></div></div>})}<p className="micro-caption">{data.entries.length} rögzített étel · {number(totals.fiber)} g rost</p></section></div>
 <div className="content-grid"><section className="panel trend-card"><div className="card-heading"><div><p className="eyebrow">AZ ELMÚLT 7 NAP</p><h2>Minden nap számít.</h2></div><span className="pill neutral">{recorded.length}/7 nap rögzítve</span></div><div className="chart" role="img" aria-label="Elmúlt hét nap kalóriabevitele; kattints egy oszlopra a nap megnyitásához">{week.map(d=>{const height=(d.totals.kcal||0)/Math.max(1,...week.map(w=>w.totals.kcal||0))*100;return <button key={d.date} className={'chart-column '+(d.date===day?'current':'')} onClick={()=>setDay(d.date)} aria-label={`${d.date}: ${number(d.totals.kcal)} kcal, ${d.entries.length} étel`}><span className="chart-value">{d.entries.length?number(d.totals.kcal):'—'}</span><span className="bar-space"><span style={{height:Math.max(3,height)+'%'}}/></span><span>{new Date(d.date+'T12:00:00').toLocaleDateString('hu-HU',{weekday:'short'})}</span></button>})}</div><div className="chart-footer"><span><strong>{number(average)}</strong> kcal / rögzített nap</span><small>Az üres napokat nem számítjuk az átlagba.</small></div></section>
 <section className="goal-card"><div className="card-heading"><span className="eyebrow">A TE IRÁNYOD</span><span>↗</span></div><h2>Kis lépések.<br/>Saját célok.</h2><div className="weight-line"><strong>{profile?.profile?.weight_kg||'—'}<small> kg</small></strong><span>→</span><strong>{profile?.profile?.target_weight_kg||'—'}<small> kg</small></strong></div><p>{profile?.profile?.target_date?`Célidőpont: ${profile.profile.target_date}`:'Állíts be egy célt, ami hozzád illik.'}</p><button onClick={openProfile}>Profil és célok <span>↗</span></button></section></div>
 {calc.warning&&<p className="notice">{calc.warning}</p>}{view==='trends'&&<section className="panel health-panel"><h2>A számok mögött</h2><div className="health-grid">{[['Becsült alapanyagcsere',calc.bmr,'kcal'],['Becsült szintentartás',calc.maintenance,'kcal'],['Rost',totals.fiber,'g'],['Cukor',totals.sugar,'g'],['Telített zsír',totals.saturated_fat,'g'],['Só',totals.salt,'g']].map(([label,value,unit])=><div key={label}><span>{label}</span><strong>{value==null?'—':number(value)} <small>{unit}</small></strong></div>)}</div><p className="muted small">A számított energiaszükséglet becslés. A hiányzó tápanyagadatok miatt a naplóösszesítés nem feltétlenül teljes.</p></section>}</>}
 {view==='diary'&&<section className="journal"><div className="section-heading"><div><p className="eyebrow">AMIT MA RÖGZÍTETTÉL</p><h2>Az étkezéseid</h2></div><button className="text-button" onClick={()=>setModal('scanner')}>▥ Beolvasás</button></div><div className="meal-grid">{Object.entries(meals).map(([id,[label,icon]])=>{const entries=data.entries.filter(e=>e.meal===id);return <article className="panel meal-card" key={id}><div className="meal-heading"><span className={'meal-icon '+id}>{icon}</span><div><h3>{label}</h3><small>{number(entries.reduce((s,e)=>s+e.nutrients.kcal,0))} kcal</small></div><button className="round-button" aria-label={`${label} hozzáadása`} onClick={()=>{setMeal(id);setModal('search')}}>+</button></div>{entries.length?entries.map(e=><div className="entry" key={e.id}><button className="entry-name" onClick={()=>choose(e.food)}><b>{e.food.name}</b><small>{e.grams} g · P {number(e.nutrients.protein)} · CH {number(e.nutrients.carbs)} · Zs {number(e.nutrients.fat)}</small></button><span>{number(e.nutrients.kcal)}</span><button aria-label={`${e.food.name} törlése`} disabled={busy} className="delete" onClick={()=>action(async()=>{await api('/api/entries/'+e.id,{method:'DELETE'});reload()})}>×</button></div>):<button className="empty-meal" onClick={()=>{setMeal(id);setModal('search')}}>Még üres a tányérod. <span>Adj hozzá valamit ↗</span></button>}</article>})}</div></section>}
 {view==='foods'&&<section className="panel library"><div className="section-heading"><h2>Saját ételkönyvtár</h2><button className="primary" onClick={()=>setModal({type:'food'})}>+ Új étel</button></div><input aria-label="Ételkeresés" placeholder="Keress név alapján…" value={query} onChange={e=>setQuery(e.target.value)}/>{foods.map(f=><button className="food-result" key={f.id} onClick={()=>choose(f)}><span><b>{f.name}</b><small>{f.brand||'Saját termék'}</small></span><span>{number(f.kcal)} <small>kcal / 100 g</small></span></button>)}{!foods.length&&<p className="muted">Még nincs találat. Hozd létre az első saját ételed.</p>}</section>}
 <footer className="page-footer"><span>kalóriamester</span><span>A fejlődés a mindennapokban kezdődik.</span></footer></main></div>
 <nav className="mobile-nav" aria-label="Mobil navigáció"><button className={view==='diary'?'active':''} onClick={()=>setView('diary')}>◫<span>Napló</span></button><button className={view==='trends'?'active':''} onClick={()=>setView('trends')}>▥<span>Trendek</span></button><button className="mobile-add" aria-label="Étel hozzáadása" onClick={()=>setModal('search')}>+</button><button className={view==='foods'?'active':''} onClick={()=>setView('foods')}>⌕<span>Ételek</span></button><button onClick={openProfile}>◎<span>Profil</span></button></nav>
 {modal==='profile'&&<ProfileForm value={profile?.profile} cancel={()=>setModal(null)} onSave={r=>{setProfile(r);setModal(null)}}/>}{modal?.type==='food'&&<FoodForm food={modal.food} barcode={modal.barcode} cancel={()=>setModal(null)} onSave={saveFood}/>}{modal==='scanner'&&<Scanner onCode={barcode} close={()=>setModal('search')}/>}
 {modal==='search'&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label="Étel hozzáadása"><div className="card-heading"><h2>Mi kerül a tányérra?</h2><button className="round-button" onClick={()=>setModal(null)} aria-label="Bezárás">×</button></div><input autoFocus placeholder="Étel keresése…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="quick-actions"><button onClick={()=>setModal('scanner')}>▥ Vonalkód beolvasása</button><button onClick={()=>setModal({type:'food'})}>+ Saját étel</button></div><form className="barcode-form" onSubmit={e=>{e.preventDefault();barcode(new FormData(e.currentTarget).get('code'))}}><input name="code" required pattern="[0-9]{6,13}" inputMode="numeric" placeholder="Vonalkód kézzel" aria-label="Vonalkód"/><button disabled={busy}>Keresés</button></form><div className="food-list">{foods.map(f=><button className="food-result" key={f.id} onClick={()=>choose(f)}><span><b>{f.name}</b><small>{f.brand||'Saját étel'}</small></span><span>{number(f.kcal)} <small>kcal / 100 g</small></span></button>)}{!foods.length&&<p className="muted">Nincs találat. Készíts saját ételt vagy olvasd be a csomagolását.</p>}</div></section></div>}
 {pick&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label="Mennyiség kiválasztása"><div className="card-heading"><span className="eyebrow">ELLENŐRIZD AZ ADAGOD</span><button className="round-button" aria-label="Bezárás" onClick={()=>setPick(null)}>×</button></div><h2>{pick.name}</h2><p className="muted">{pick.brand} · {pick.confidence==='incomplete'?'Hiányos adat':pick.confidence==='estimated'?'Becsült adat':'Pontosként megadott adat'}</p><div className="portion-calories">{number(pick.kcal*grams/100)} <small>kcal</small></div><div className="amount">{[50,100,150,200].map(g=><button key={g} className={Number(grams)===g?'selected':''} onClick={()=>setGrams(g)}>{g} g</button>)}{pick.serving_size_g>0&&<button onClick={()=>setGrams(pick.serving_size_g)}>Csomag</button>}</div><div className="grid"><label>Mennyiség (g)<input type="number" min="1" value={grams} onChange={e=>setGrams(e.target.value)}/></label><label>Étkezés<select value={meal} onChange={e=>setMeal(e.target.value)}>{Object.entries(meals).map(([id,[label]])=><option key={id} value={id}>{label}</option>)}</select></label></div><div className="portion-macros">{macros.map(([k,n,c])=><span key={k}><i style={{background:c}}/>{n} <b>{number(pick[k]*grams/100)} g</b></span>)}</div><button className="primary full" disabled={busy||!(Number(grams)>0)} onClick={()=>action(async()=>{await api('/api/entries',{method:'POST',body:JSON.stringify({food_id:pick.id,log_date:day,meal,grams:Number(grams)})});setPick(null);reload()})}>{busy?'Mentés…':'+ Hozzáadás a naplóhoz'}</button><button className="text-button full" onClick={()=>{setModal({type:'food',food:pick});setPick(null)}}>Termékadatok szerkesztése</button></section></div>}
 </>;
}
