import React, {useEffect, useRef, useState} from 'react';

import {BrowserMultiFormatReader} from '@zxing/browser';
import {BarcodeFormat, DecodeHintType} from '@zxing/library';


export const api=async(path,opt={})=>{const token=localStorage.token; const r=await fetch(path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(r.status===401){localStorage.removeItem('token');location.reload()}if(!r.ok)throw new Error(await r.text());return r.json()}
export const today=()=>new Date().toLocaleDateString('sv-SE'); const mnames={breakfast:'Reggeli',lunch:'Ebéd',dinner:'Vacsora',snack:'Snack'};
export function Login({done}){const [username,setU]=useState('');const [password,setP]=useState('');const [err,setE]=useState('');async function go(e){e.preventDefault();try{let x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});localStorage.token=x.token;done()}catch{setE('Hibás belépési adatok.')}}return <main className="login"><section><span className="logo">●</span><h1>KalóriaMester</h1><p>Privát táplálkozási naplód</p><form onSubmit={go}><input placeholder="Felhasználónév" value={username} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Jelszó" value={password} onChange={e=>setP(e.target.value)}/>{err&&<small>{err}</small>}<button>Belépés</button></form></section></main>}
export function Scanner({onCode,close}){
 const video=useRef();const [error,setError]=useState('');
 useEffect(()=>{let active=true,controls;const hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E]);const reader=new BrowserMultiFormatReader(hints);
 reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}},audio:false},video.current,(result,err,control)=>{if(result&&active){active=false;control.stop();navigator.vibrate?.(120);onCode(result.getText())}}).then(c=>{controls=c;if(!active)c.stop()}).catch(()=>{if(active)setError('A kamera nem indítható. Ellenőrizd a kameraengedélyt, vagy írd be kézzel a vonalkódot.')});
 return()=>{active=false;controls?.stop()};
 },[]);
 return <div className="scanner"><header><b>Vonalkód beolvasása</b><button onClick={close}>Bezárás</button></header><video ref={video} muted playsInline/><div className="scanline"/><p>{error||'Irányítsd a kamerát a vonalkódra'}</p></div>;
}
export function FoodForm({food,barcode,onSave,cancel}){const blank={name:'',brand:'',barcode:barcode||'',serving_size_g:'',kcal:0,protein:0,carbs:0,fat:0,fiber:'',sugar:'',saturated_fat:'',salt:'',source:'manual',confidence:'precise',verified_by_user:false,notes:''};const [x,setX]=useState(food||blank);const update=(k,v)=>setX({...x,[k]:v});async function submit(e){e.preventDefault();let payload={...x};['serving_size_g','kcal','protein','carbs','fat','fiber','sugar','saturated_fat','salt'].forEach(k=>payload[k]=payload[k]===''?null:Number(payload[k]));onSave(await api(`/api/foods${food?'/'+food.id:''}`,{method:food?'PUT':'POST',body:JSON.stringify(payload)}))}return <div className="sheet"><form onSubmit={submit}><header><h2>{food?'Étel szerkesztése':'Új saját étel'}</h2><button type="button" onClick={cancel}>×</button></header><label>Név<input required value={x.name} onChange={e=>update('name',e.target.value)}/></label><label>Márka<input value={x.brand||''} onChange={e=>update('brand',e.target.value)}/></label><label>Vonalkód<input inputMode="numeric" value={x.barcode||''} onChange={e=>update('barcode',e.target.value)}/></label><label>Teljes csomag (g)<input type="number" value={x.serving_size_g||''} onChange={e=>update('serving_size_g',e.target.value)}/></label><h3>100 grammra vetítve</h3><div className="grid">{[['kcal','kcal'],['protein','fehérje (g)'],['carbs','szénhidrát (g)'],['fat','zsír (g)'],['fiber','rost (g)'],['sugar','cukor (g)'],['saturated_fat','telített zsír (g)'],['salt','só (g)']].map(([k,n])=><label key={k}>{n}<input required={['kcal','protein','carbs','fat'].includes(k)} type="number" step="0.01" min="0" value={x[k]??''} onChange={e=>update(k,e.target.value)}/></label>)}</div><label>Megjegyzés<textarea value={x.notes||''} onChange={e=>update('notes',e.target.value)}/></label><button>Mentés</button></form></div>}
export function ProfileForm({value,onSave,cancel}){const [x,setX]=useState(value||{sex:'other',birth_date:'',height_cm:'',weight_kg:'',activity:'sedentary',target_weight_kg:'',target_date:'',weekly_loss_kg:.5,calorie_override:''});const set=(k,v)=>setX({...x,[k]:v});async function submit(e){e.preventDefault();const p={...x};['height_cm','weight_kg','target_weight_kg','calorie_override'].forEach(k=>p[k]=p[k]===''||p[k]==null?null:Number(p[k]));p.birth_date=p.birth_date||null;p.target_date=p.target_date||null;p.weekly_loss_kg=Number(p.weekly_loss_kg);onSave(await api('/api/profile',{method:'PUT',body:JSON.stringify(p)}))}return <div className="sheet"><form onSubmit={submit}><header><h2>Profil és cél</h2><button type="button" onClick={cancel}>×</button></header><p className="hint">A számítás tájékoztató jellegű; nem helyettesít orvosi vagy dietetikusi tanácsot.</p><div className="grid"><label>Nem<select value={x.sex} onChange={e=>set('sex',e.target.value)}><option value="female">Nő</option><option value="male">Férfi</option><option value="other">Egyéb / nem adom meg</option></select></label><label>Születési dátum<input required type="date" value={x.birth_date||''} onChange={e=>set('birth_date',e.target.value)}/></label><label>Magasság (cm)<input required type="number" min="80" value={x.height_cm||''} onChange={e=>set('height_cm',e.target.value)}/></label><label>Jelenlegi testsúly (kg)<input required type="number" step="0.1" value={x.weight_kg||''} onChange={e=>set('weight_kg',e.target.value)}/></label></div><label>Aktivitás<select value={x.activity} onChange={e=>set('activity',e.target.value)}><option value="sedentary">Ülő életmód</option><option value="light">Enyhén aktív</option><option value="moderate">Közepesen aktív</option><option value="active">Aktív</option><option value="very_active">Nagyon aktív</option></select></label><h3>Fogyási cél</h3><div className="grid"><label>Cél testsúly (kg)<input type="number" step="0.1" value={x.target_weight_kg||''} onChange={e=>set('target_weight_kg',e.target.value)}/></label><label>Célidőpont<input type="date" value={x.target_date||''} onChange={e=>set('target_date',e.target.value)}/></label><label>Fogyás hetente (kg)<input required type="number" min="0" max="2" step="0.1" value={x.weekly_loss_kg} onChange={e=>set('weekly_loss_kg',e.target.value)}/></label><label>Egyéni kcal-cél (opcionális)<input type="number" min="800" value={x.calorie_override||''} onChange={e=>set('calorie_override',e.target.value)}/></label></div><button>Profil és cél mentése</button></form></div>}
