import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserMultiFormatReader} from '@zxing/browser';
import {BarcodeFormat, DecodeHintType} from '@zxing/library';
import './style.css';

const api=async(path,opt={})=>{const token=localStorage.token; const r=await fetch(path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(r.status===401){localStorage.removeItem('token');location.reload()}if(!r.ok)throw new Error(await r.text());return r.json()}
const today=()=>new Date().toISOString().slice(0,10); const mnames={breakfast:'Reggeli',lunch:'Ebéd',dinner:'Vacsora',snack:'Snack'};
function Login({done}){const [username,setU]=useState('');const [password,setP]=useState('');const [err,setE]=useState('');async function go(e){e.preventDefault();try{let x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});localStorage.token=x.token;done()}catch{setE('Hibás belépési adatok.')}}return <main className="login"><section><span className="logo">●</span><h1>KalóriaMester</h1><p>Privát táplálkozási naplód</p><form onSubmit={go}><input placeholder="Felhasználónév" value={username} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Jelszó" value={password} onChange={e=>setP(e.target.value)}/>{err&&<small>{err}</small>}<button>Belépés</button></form></section></main>}
function Scanner({onCode,close}){const video=useRef();const reader=useRef();const [error,setError]=useState('');useEffect(()=>{let active=true;const run=async()=>{try{let hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E]);reader.current=new BrowserMultiFormatReader(hints);await reader.current.decodeFromVideoDevice(undefined,video.current,(res)=>{if(res&&active){navigator.vibrate?.(120);active=false;reader.current.reset();onCode(res.getText())}})}catch(e){setError('A kamera nem indítható. HTTPS és kameraengedély szükséges.')}};run();return()=>{active=false;reader.current?.reset() }},[]);return <div className="scanner"><header><b>Vonalkód beolvasása</b><button onClick={close}>Bezárás</button></header><video ref={video}/><div className="scanline"/><p>{error||'Irányítsd a kamerát a vonalkódra'}</p></div>}
function FoodForm({food,barcode,onSave,cancel}){const blank={name:'',brand:'',barcode:barcode||'',serving_size_g:'',kcal:0,protein:0,carbs:0,fat:0,fiber:'',sugar:'',saturated_fat:'',salt:'',source:'manual',confidence:'precise',verified_by_user:false,notes:''};const [x,setX]=useState(food||blank);const update=(k,v)=>setX({...x,[k]:v});async function submit(e){e.preventDefault();let payload={...x};['serving_size_g','kcal','protein','carbs','fat','fiber','sugar','saturated_fat','salt'].forEach(k=>payload[k]=payload[k]===''?null:Number(payload[k]));onSave(await api(`/api/foods${food?'/'+food.id:''}`,{method:food?'PUT':'POST',body:JSON.stringify(payload)}))}return <div className="sheet"><form onSubmit={submit}><header><h2>{food?'Étel szerkesztése':'Új saját étel'}</h2><button type="button" onClick={cancel}>×</button></header><label>Név<input required value={x.name} onChange={e=>update('name',e.target.value)}/></label><label>Márka<input value={x.brand||''} onChange={e=>update('brand',e.target.value)}/></label><label>Vonalkód<input inputMode="numeric" value={x.barcode||''} onChange={e=>update('barcode',e.target.value)}/></label><label>Teljes csomag (g)<input type="number" value={x.serving_size_g||''} onChange={e=>update('serving_size_g',e.target.value)}/></label><h3>100 grammra vetítve</h3><div className="grid">{[['kcal','kcal'],['protein','fehérje (g)'],['carbs','szénhidrát (g)'],['fat','zsír (g)'],['fiber','rost (g)'],['sugar','cukor (g)'],['saturated_fat','telített zsír (g)'],['salt','só (g)']].map(([k,n])=><label key={k}>{n}<input required={['kcal','protein','carbs','fat'].includes(k)} type="number" step="0.01" min="0" value={x[k]??''} onChange={e=>update(k,e.target.value)}/></label>)}</div><label>Megjegyzés<textarea value={x.notes||''} onChange={e=>update('notes',e.target.value)}/></label><button>Mentés</button></form></div>}
function App(){
 const [logged,setLogged]=useState(!!localStorage.token),[day,setDay]=useState(today()),[data,setData]=useState({entries:[],totals:{}}),[modal,setModal]=useState(null),[query,setQuery]=useState(''),[foods,setFoods]=useState([]),[pick,setPick]=useState(null),[grams,setGrams]=useState(100),[meal,setMeal]=useState('breakfast');
 const load=()=>api('/api/day/'+day).then(setData); useEffect(()=>{if(logged)load()},[logged,day]); useEffect(()=>{if(query.length>1)api('/api/foods?q='+encodeURIComponent(query)).then(setFoods)},[query]);
 if(!logged)return <Login done={()=>setLogged(true)}/>;
 async function code(v){setModal(null);try{const r=await api('/api/barcode/'+v);if(r.found){setPick(r.food);setGrams(100)}else setModal(<FoodForm barcode={v} cancel={()=>setModal(null)} onSave={f=>{setModal(null);setPick(f)}}/>)}catch{alert('A termék keresése nem sikerült.')}}
 async function add(){await api('/api/entries',{method:'POST',body:JSON.stringify({food_id:pick.id,log_date:day,meal,grams})});setPick(null);load()}
 return <><main><nav><div className="brand">● KalóriaMester</div><button onClick={()=>{localStorage.clear();setLogged(false)}}>Kilépés</button></nav>
 <section className="day"><button onClick={()=>setDay(new Date(new Date(day+'T12:00').getTime()-864e5).toISOString().slice(0,10))}>‹</button><input type="date" value={day} onChange={e=>setDay(e.target.value)}/><button onClick={()=>setDay(new Date(new Date(day+'T12:00').getTime()+864e5).toISOString().slice(0,10))}>›</button></section>
 <section className="summary"><div><strong>{Math.round(data.totals.kcal||0)}</strong><span>kcal</span></div>{[['protein','Fehérje'],['carbs','Szénhidrát'],['fat','Zsír']].map(([k,n])=><div key={k}><strong>{Math.round(data.totals[k]||0)}g</strong><span>{n}</span></div>)}</section>
 <section className="add"><input placeholder="Étel keresése…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="scan" onClick={()=>setModal(<Scanner onCode={code} close={()=>setModal(null)}/>)}>▣ Beolvasás</button>{foods.length>0&&<div className="results">{foods.map(f=><button key={f.id} onClick={()=>{setPick(f);setGrams(100);setQuery('');setFoods([])}}>{f.name}<small>{f.kcal} kcal / 100 g</small></button>)}</div>}<button className="manual" onClick={()=>setModal(<FoodForm cancel={()=>setModal(null)} onSave={f=>{setModal(null);setPick(f)}}/>)}>+ Saját étel</button></section>
 {pick&&<section className="confirm"><button className="close" onClick={()=>setPick(null)}>×</button><b>{pick.name}</b><small>{pick.brand||'Saját adat'} · {pick.confidence==='incomplete'?'Hiányos adat':pick.confidence==='estimated'?'Becsült adat':'Pontos adat'}</small><div className="amount">{[50,100,150,200,pick.serving_size_g].filter(Boolean).map(x=><button className={grams==x?'selected':''} onClick={()=>setGrams(x)} key={x}>{x==pick.serving_size_g?'Teljes csomag':x+' g'}</button>)}</div><input type="number" min="1" value={grams} onChange={e=>setGrams(e.target.value)}/><select value={meal} onChange={e=>setMeal(e.target.value)}>{Object.entries(mnames).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><p>{Math.round(pick.kcal*grams/100)} kcal · P {Math.round(pick.protein*grams/100)} g · CH {Math.round(pick.carbs*grams/100)} g</p><button onClick={add}>Hozzáadás: {mnames[meal]}</button></section>}
 <section className="meals">{Object.keys(mnames).map(m=><article key={m}><h2>{mnames[m]}</h2>{data.entries.filter(e=>e.meal===m).map(e=><div className="entry" key={e.id}><span><b>{e.food.name}</b><small>{e.grams} g · P {e.nutrients.protein} · CH {e.nutrients.carbs} · Zs {e.nutrients.fat}</small></span><b>{Math.round(e.nutrients.kcal)} kcal</b><button onClick={async()=>{await api('/api/entries/'+e.id,{method:'DELETE'});load()}}>×</button></div>)}{!data.entries.some(e=>e.meal===m)&&<p className="empty">Még nincs étel</p>}</article>)}</section></main>{modal}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
